// Find this line:
AFFECT_OTHER_WORLD_NORTH_REAPER_ROOM_DEBUFF = 638,

// Add after it:
#if defined(__MOUNT_UPGRADE__)
	AFFECT_SKILL_MOUNT_UPGRADE_NIMBLE = 639,
	AFFECT_SKILL_MOUNT_UPGRADE_EXP = 640,
	AFFECT_SKILL_MOUNT_UPGRADE_SPEED = 641,
	AFFECT_SKILL_MOUNT_UPGRADE_GYENONGGONG = 642,
	AFFECT_SKILL_MOUNT_UPGRADE_INVINCIBLITIY = 643,
	AFFECT_SKILL_MOUNT_UPGRADE_KNOCKBACK = 644,
	AFFECT_SKILL_MOUNT_UPGRADE_TO_STRONG = 645,
	AFFECT_SKILL_MOUNT_UPGRADE_EFFECT_UP = 646,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_STR = 647,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_HP = 648,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_MOVE = 649,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_IMMUNE = 650,
	AFFECT_SKILL_MOUNT_UPGRADE_HIT_PCT = 651,
#endif
