// Find this block in `kPointOnTypes[]`:
	{ "SUNGMA_STR", POINT_SUNGMA_STR },
	{ "SUNGMA_HP", POINT_SUNGMA_HP },
	{ "SUNGMA_MOVE", POINT_SUNGMA_MOVE },
	{ "SUNGMA_IMMUNE", POINT_SUNGMA_IMMUNE },
	{ "HIT_PCT", POINT_HIT_PCT },

// Add after it:
	{ "MOUNT_UPGRADE_SPEED", POINT_ATT_SPEED },
	{ "MOUNT_UPGRADE_NIMBLE", POINT_MOV_SPEED },
	{ "MOUNT_UPGRADE_NO_KNOCKBACK", POINT_MOUNT_NO_KNOCKBACK },
	{ "MOUNT_UPGRADE_SUNGMA_STR", POINT_SUNGMA_STR },
	{ "MOUNT_UPGRADE_SUNGMA_HP", POINT_SUNGMA_HP },
	{ "MOUNT_UPGRADE_SUNGMA_MOVE", POINT_SUNGMA_MOVE },
	{ "MOUNT_UPGRADE_SUNGMA_IMMUNE", POINT_SUNGMA_IMMUNE },
