#pragma once

#include "ItemData.h"

#if defined(ENABLE_MOUNT_UPGRADE_SYSTEM)
const int HORSE_MAX_LEVEL = 40;
#endif

enum EDragonSoulDeckType
{
	DS_DECK_1,
	DS_DECK_2,
	DS_DECK_MAX_NUM,
};

enum EDragonSoulGradeTypes
{
	DRAGON_SOUL_GRADE_NORMAL,
	DRAGON_SOUL_GRADE_BRILLIANT,
	DRAGON_SOUL_GRADE_RARE,
	DRAGON_SOUL_GRADE_ANCIENT,
	DRAGON_SOUL_GRADE_LEGENDARY,
#if defined(ENABLE_DS_GRADE_MYTH)
	DRAGON_SOUL_GRADE_MYTH,
#endif
	DRAGON_SOUL_GRADE_MAX,
};

enum EDragonSoulStepTypes
{
	DRAGON_SOUL_STEP_LOWEST,
	DRAGON_SOUL_STEP_LOW,
	DRAGON_SOUL_STEP_MID,
	DRAGON_SOUL_STEP_HIGH,
	DRAGON_SOUL_STEP_HIGHEST,
	DRAGON_SOUL_STEP_MAX,
};

enum EDragonSoulStrengthTypes
{
	DRAGON_SOUL_STRENGTH_MAX = 7,
};

enum EItemVnum
{
	ITEM_VNUM_SCROLL_OF_CORRECTION = 71109,
#if defined(ENABLE_MINI_GAME_RUMI)
	ITEM_VNUM_RUMI_CARD_PIECE = 79505,
	ITEM_VNUM_RUMI_CARD_PACK = 79506,
#endif
#if defined(ENABLE_MINI_GAME_YUTNORI)
	ITEM_VNUM_YUT_PIECE = 79507,
	ITEM_VNUM_YUT_BOARD = 79508,
#endif
#if defined(ENABLE_MINI_GAME_CATCH_KING)
	ITEM_VNUM_CATCH_KING_PIECE = 79603,
	ITEM_VNUM_CATCH_KING_PACK = 79604,
#endif
#if defined(ENABLE_SET_ITEM)
	ITEM_VNUM_SET_CLEAR_SCROLL = 39115,
#endif
#if defined(ENABLE_AURA_COSTUME_SYSTEM)
	ITEM_VNUM_AURA_CLEAR = 89999,
#endif
#if defined(ENABLE_SNOWFLAKE_STICK_EVENT)
	ITEM_VNUM_SNOWFLAKE_STICK = 70612,
	ITEM_VNUM_SNOWFLAKE_STICK_EVENT_MOUNT = 70614,
	ITEM_VNUM_SNOWFLAKE_STICK_EVENT_PET = 70615,
#endif
#if defined(ENABLE_GEM_CONVERTER)
	ITEM_VNUM_GEM_CONVERTER = 50935,
	ITEM_VNUM_GEM_STONE = 50926,
#endif
};

typedef struct SValueName
{
	const char* c_pszName;
	POINT_VALUE lValue;
} TValueName;

POINT_VALUE GetApplyTypeByName(const char* c_pszApplyName);
