// Find this line:
NEW_AFFECT_OTHER_WORLD_NORTH_REAPER_ROOM_DEBUFF = 638,

// Add after it:
#if defined(ENABLE_MOUNT_UPGRADE_SYSTEM)
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_NIMBLE = 639,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_EXP = 640,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_SPEED = 641,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_GYENONGGONG = 642,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_INVINCIBLITIY = 643,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_KNOCKBACK = 644,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_TO_STRONG = 645,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_EFFECT_UP = 646,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_STR = 647,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_HP = 648,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_MOVE = 649,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_IMMUNE = 650,
		NEW_AFFECT_SKILL_MOUNT_UPGRADE_HIT_PCT = 651,
#endif
