// Find this line:
PyModule_AddIntConstant(poModule, "AFFECT_OTHER_WORLD_NORTH_REAPER_ROOM_DEBUFF", CInstanceBase::NEW_AFFECT_OTHER_WORLD_NORTH_REAPER_ROOM_DEBUFF);

// Add after it:
#if defined(ENABLE_MOUNT_UPGRADE_SYSTEM)
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_NIMBLE", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_NIMBLE);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_EXP", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_EXP);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_SPEED", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_SPEED);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_GYENONGGONG", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_GYENONGGONG);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_INVINCIBLITIY", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_INVINCIBLITIY);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_KNOCKBACK", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_KNOCKBACK);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_TO_STRONG", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_TO_STRONG);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_EFFECT_UP", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_EFFECT_UP);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_STR", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_STR);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_HP", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_HP);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_MOVE", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_MOVE);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_IMMUNE", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_IMMUNE);
	PyModule_AddIntConstant(poModule, "AFFECT_SKILL_MOUNT_UPGRADE_HIT_PCT", CInstanceBase::NEW_AFFECT_SKILL_MOUNT_UPGRADE_HIT_PCT);
#endif
